theme: jekyll-theme-cayman
#available themes: cayman, slate, merlot, time-machine, minimal, leap-day, modernist, hacker, midnight, architect, tactile, dinky
#preview: https://pages-themes.github.io/cayman/ 
#repository: https://github.com/pages-themes/cayman

baseurl: "/CARLA"
url: "https://conceptresearch.github.io/"
