---
title: "CARLA_2022_accommodation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Accommodation

We have compiled a list of hotels near the venue to help you prepare for your trip to Berlin.

***

**You can book a room in Adina Apartment Hotel Berlin Hackescher Markt.**\
All rooms have wi-fi.\
There are *double rooms for single use at 89€* and *double rooms from 89€*. Breakfast is not included, but available in the hotel.\
10 minute walking distance from the venue.

*   [Website](https://www.adinahotels.com/de/)
*   [Booking](https://www.booking.com/hotel/de/adina-apartment-berlin-hackescher-markt.en-gb.html?aid=304142;label=gen173nr-1FCAEoggI46AdIM1gEaDuIAQGYAQm4ARfIAQ_YAQHoAQH4AQuIAgGoAgO4AuKK9I8GwAIB0gIkMWRiYjdlODMtMmI2OS00NmQ3LTkxYjctYWY3ZDVhMmNhZTdm2AIG4AIB;sid=5e4c8e609ebef7f5af2edbe8594dff9a;all_sr_blocks=25533201_91469022_2_2_0;checkin=2022-02-10;checkout=2022-02-11;dest_id=255332;dest_type=hotel;dist=0;group_adults=2;group_children=0;hapos=1;highlighted_blocks=25533201_91469022_2_2_0;hpos=1;matching_block_id=25533201_91469022_2_2_0;no_rooms=1;req_adults=2;req_children=0;room1=A%2CA;sb_price_type=total;sr_order=popularity;sr_pri_blocks=25533201_91469022_2_2_0__9356;srepoch=1643972102;srpvid=c8564cc299610097;type=total;ucfs=1&#hotelTmpl)
*   An der Spandauer Brücke 11, 10178 Berlin
*   +49 30 209 6980

***

**You can book a room in ARCOTEL John F Berlin.**\
All rooms have wi-fi.\
There are *single rooms from 95€* and *double rooms from 105€.* Breakfast is an extra 15€.\
7 minute walking distance from the venue.

*   [Website](https://johnf.arcotel.com/de/)
*   [Booking](https://www.booking.com/hotel/de/john-f.en-gb.html?aid=304142;label=gen173nr-1FCAEoggI46AdIM1gEaDuIAQGYAQm4ARfIAQ_YAQHoAQH4AQuIAgGoAgO4AuKK9I8GwAIB0gIkMWRiYjdlODMtMmI2OS00NmQ3LTkxYjctYWY3ZDVhMmNhZTdm2AIG4AIB;sid=5e4c8e609ebef7f5af2edbe8594dff9a;all_sr_blocks=2794802_97056222_0_2_0;checkin=2022-02-09;checkout=2022-02-10;dest_id=27948;dest_type=hotel;dist=0;group_adults=2;group_children=0;hapos=1;highlighted_blocks=2794802_97056222_0_2_0;hpos=1;matching_block_id=2794802_97056222_0_2_0;no_rooms=1;req_adults=2;req_children=0;room1=A%2CA;sb_price_type=total;sr_order=popularity;sr_pri_blocks=2794802_97056222_0_2_0__9887;srepoch=1643972166;srpvid=15374ce27f210155;type=total;ucfs=1&#hotelTmpl)
*   Werderscher Markt 11, 10117 Berlin
*   +49 30 40 50 46-0 

***

**You can book a room in Best Western Hotel am Spittelmarkt.**\
All rooms have wi-fi.\
There are *double rooms for single use at 59€* and *double rooms from 59€. * Breakfast is an additional 13€.\
20 minute walking distance from the venue.

*   [Website](https://www.bestwestern.com/de_DE/book/hotels-in-berlin/best-western-hotel-am-spittelmarkt/propertyCode.95382.html) 
*   [Booking](https://www.booking.com/hotel/de/am-spittelmarkt.en-gb.html?aid=304142;label=gen173nr-1FCAEoggI46AdIM1gEaDuIAQGYAQm4ARfIAQ_YAQHoAQH4AQuIAgGoAgO4AuKK9I8GwAIB0gIkMWRiYjdlODMtMmI2OS00NmQ3LTkxYjctYWY3ZDVhMmNhZTdm2AIG4AIB;sid=5e4c8e609ebef7f5af2edbe8594dff9a;checkin=2022-02-10;checkout=2022-02-11;dest_id=73307;dest_type=hotel;dist=0;group_adults=2;group_children=0;hapos=1;hpos=1;no_rooms=1;req_adults=2;req_children=0;room1=A%2CA;sb_price_type=total;soh=1;sr_order=popularity;srepoch=1643972530;srpvid=f0814d987a2100e4;type=total;ucfs=1&#no_availability_msg)
*   Neue Grunstrasse 28, 10179 Berlin
*   +49 30 31161500

***

**You can book a room in MEININGER Hotel Mitte "Humboldthaus".**\
All rooms have wi-fi.\
There are *single rooms from 59€* and *double rooms from 66€.* Breakfast is included.\
10 minute walking distance from the venue.

*   [Website](https://www.meininger-hotels.com/en/hotels/berlin/hotel-berlin-center/)
*   [Booking](https://www.booking.com/hotel/de/meininger-berlin-mitte.en-gb.html?aid=304142;label=gen173nr-1FCAEoggI46AdIM1gEaDuIAQGYAQm4ARfIAQ_YAQHoAQH4AQuIAgGoAgO4AuKK9I8GwAIB0gIkMWRiYjdlODMtMmI2OS00NmQ3LTkxYjctYWY3ZDVhMmNhZTdm2AIG4AIB;sid=5e4c8e609ebef7f5af2edbe8594dff9a;all_sr_blocks=24029502_91468368_0_2_0;checkin=2022-02-09;checkout=2022-02-10;dist=0;group_adults=2;group_children=0;hapos=1;highlighted_blocks=24029502_91468368_0_2_0;hpos=1;matching_block_id=24029502_91468368_0_2_0;no_rooms=1;req_adults=2;req_children=0;room1=A%2CA;sb_price_type=total;sr_order=distance_from_search;sr_pri_blocks=24029502_91468368_0_2_0__5650;srepoch=1643972223;srpvid=1f084cfa8c4d00a0;type=total;ucfs=1&#hotelTmpl)
*   Oranienburger Str. 67-68, 10117 Berlin
*   +49 30 3187 9816

***

**You can book a room in Mercure Hotel&Residenz Berlin Checkpoint Charlie.**\
All rooms have wi-fi.\
There are *single rooms from 88€* and *double rooms from 98€.* Breakfast is an additional 15-20€.\
20 minute walking distance from the venue, or you can take the U6 from Kochstraße to Unter den Linden.

*   [Website](https://mercurehotelcharlie.atberlinhotels.com)
*   [Booking](https://www.booking.com/hotel/de/mercurecheckpointcharlie.en-gb.html?aid=304142;label=gen173nr-1FCAEoggI46AdIM1gEaDuIAQGYAQm4ARfIAQ_YAQHoAQH4AQuIAgGoAgO4AuKK9I8GwAIB0gIkMWRiYjdlODMtMmI2OS00NmQ3LTkxYjctYWY3ZDVhMmNhZTdm2AIG4AIB;sid=5e4c8e609ebef7f5af2edbe8594dff9a;all_sr_blocks=6141148_265873872_2_2_0;checkin=2022-02-10;checkout=2022-02-11;dest_id=61411;dest_type=hotel;dist=0;group_adults=2;group_children=0;hapos=1;highlighted_blocks=6141148_265873872_2_2_0;hpos=1;matching_block_id=6141148_265873872_2_2_0;no_rooms=1;req_adults=2;req_children=0;room1=A%2CA;sb_price_type=total;sr_order=popularity;sr_pri_blocks=6141148_265873872_2_2_0__7900;srepoch=1643972458;srpvid=c2904d706f2b008a;type=total;ucfs=1&#hotelTmpl)
*   Schützenstraße 11, 10117 Berlin
*   +49 30 206320

***

**You can book a room in Monbijou Hotel Berlin.**\
All rooms have wi-fi.\
There are *double rooms for single use from 79€* and *double rooms from 79€*. Breakfast is not included, but available.\
10 minute walking distance from the venue.

*   [Website](https://www.monbijouhotel.com/)
*   [Booking](https://www.booking.com/hotel/de/monbijou.en-gb.html?aid=304142;label=gen173nr-1FCAEoggI46AdIM1gEaDuIAQGYAQm4ARfIAQ_YAQHoAQH4AQuIAgGoAgO4AuKK9I8GwAIB0gIkMWRiYjdlODMtMmI2OS00NmQ3LTkxYjctYWY3ZDVhMmNhZTdm2AIG4AIB;sid=5e4c8e609ebef7f5af2edbe8594dff9a;all_sr_blocks=46911502_201668512_0_0_0;checkin=2022-02-08;checkout=2022-02-09;dest_id=469115;dest_type=hotel;dist=0;group_adults=2;group_children=0;hapos=1;highlighted_blocks=46911502_201668512_0_0_0;hpos=1;matching_block_id=46911502_201668512_0_0_0;no_rooms=1;req_adults=2;req_children=0;room1=A%2CA;sb_price_type=total;sr_order=popularity;sr_pri_blocks=46911502_201668512_0_0_0__8900;srepoch=1643972284;srpvid=c2364d1daf2d015e;type=total;ucfs=1&#hotelTmpl)
*   Monbijoupl. 1, 10178 Berlin
*   +49 30 616 20 300

***

**You can book a room in Select Hotel Berlin Gendarmenmarkt.**\
All rooms have wi-fi.\
There are *single rooms from 44€* and *double rooms from 60€.* Breakfast is an additional 15€.\
15 minute walking distance from the venue.

*   [Website](https://www.select-hotels.com/hotels/select-hotel-berlin-gendarmenmarkt/)
*   [Booking](https://www.booking.com/hotel/de/winter-s-gendarmenmarkt-berlin-mitte.en-gb.html?aid=304142;label=gen173nr-1FCAEoggI46AdIM1gEaDuIAQGYAQm4ARfIAQ_YAQHoAQH4AQuIAgGoAgO4AuKK9I8GwAIB0gIkMWRiYjdlODMtMmI2OS00NmQ3LTkxYjctYWY3ZDVhMmNhZTdm2AIG4AIB;sid=5e4c8e609ebef7f5af2edbe8594dff9a;all_sr_blocks=2260601_202688596_0_2_0;checkin=2022-02-09;checkout=2022-02-10;dest_id=22606;dest_type=hotel;dist=0;group_adults=2;group_children=0;hapos=1;highlighted_blocks=2260601_202688596_0_2_0;hpos=1;matching_block_id=2260601_202688596_0_2_0;no_rooms=1;req_adults=2;req_children=0;room1=A%2CA;sb_price_type=total;sr_order=popularity;sr_pri_blocks=2260601_202688596_0_2_0__6900;srepoch=1643972342;srpvid=7a4e4d3a18190139;type=total;ucfs=1&#hotelTmpl)
*   Charlottenstraße 66, 10117 Berlin
*   +49 30 20 60 50 0

***

**You can book a room in Select Hotel Berlin The Wall.**\
All rooms have wi-fi.\
There are *single rooms from 49€* and *double rooms from 59€.* Breakfast is an additional 15€.\
20 minute walking distance from the venue, or you can take the U6 from Kochstraße to Unter den Linden.

*   [Website](https://www.select-hotels.com/hotels/select-hotel-berlin-the-wall/)
*   [Booking](https://www.booking.com/hotel/de/winters-berlin-mitte-the-wall-checkpoint-charlie.en-gb.html?aid=304142;label=gen173nr-1FCAEoggI46AdIM1gEaDuIAQGYAQm4ARfIAQ_YAQHoAQH4AQuIAgGoAgO4AuKK9I8GwAIB0gIkMWRiYjdlODMtMmI2OS00NmQ3LTkxYjctYWY3ZDVhMmNhZTdm2AIG4AIB;sid=5e4c8e609ebef7f5af2edbe8594dff9a;all_sr_blocks=42383102_202649003_0_2_0;checkin=2022-02-10;checkout=2022-02-11;dest_id=423831;dest_type=hotel;dist=0;group_adults=2;group_children=0;hapos=1;highlighted_blocks=42383102_202649003_0_2_0;hpos=1;matching_block_id=42383102_202649003_0_2_0;no_rooms=1;req_adults=2;req_children=0;room1=A%2CA;sb_price_type=total;sr_order=popularity;sr_pri_blocks=42383102_202649003_0_2_0__6469;srepoch=1643972410;srpvid=f2f44d5c53b100bd;type=total;ucfs=1&#hotelTmpl)
*   Zimmerstraße 88, 10117 Berlin
*   +49 30 308 777 0



