## Venue

CARLA 2022 will take place in Dorotheenstr. 24, room 1.101/1.102/1.103 of Humboldt-Universität zu Berlin. We hope that by August, travelling will be possible again... in that case, here is some practical information to help you plan your trip.

You will have a range of options for accommodation that are close to the university. Conerning food, you can choose between many different restaurants and cafés around the campus.

1. Getting to Berlin via plane
*	BER Airport
    +	Train connection to the inner city: at least every 40 minutes
    +	Travelling time: app. 30-50 minutes
    +	Alternatively, you can take a taxi (~45€)
*	Leipzig/Halle
    +	Distance from Berlin: app. 180km
    +	Train connections to Berlin from Leipzig/Halle Airport at least every 30 minutes
    +	Travelling time: app. 1,5-2,5 hours
*	Dresden
    +	Distance from Berlin: app. 190km
    +	Train connections to Berlin from Dresden Airport at least every 1,5 hours
    +	Travelling time: app. 2,5 hours
*	Hannover
    +	Distance from Berlin: app. 300km
    +	Train connections to Berlin from Hannover Airport every 30 minutes
    +	Travelling time: app. 2,5-3 hours
*	Hamburg
    +	Distance from Berlin: app. 300km
    +	Train connections to Berlin from Hamburg Airport at least every hour
    +	Travelling time: app. 2,5-3 hours


2. Train & Bus
*	[Deutsche Bahn homepage](https://www.bahn.de/)
*	[BVG website](https://www.bvg.de/en) (subway & trams)
    +	The metro stations closest to the university are U Friedrichstraße and U Unter den Linden
    +	The closest tram stations are Am Kupfergraben, Universitätsstraße and Friedrichstraße
*	[S-Bahn Berlin website](https://sbahn.berlin/en/) (other trains within the city)
    +	The station closest to the university is S-Bahnhof Friedrichstraße
